name: Deploy

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: promenade/promenade-client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environmental variables
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          export BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          if [[ $BRANCH == 'main'  ]]; then
              echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
              echo "CHART=testnet"
          else
              echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
              echo "CHART=testnet"
          fi
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: 1.22.2
          helm: 3.6.3
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      - run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > /tmp/config
          export KUBECONFIG=/tmp/config
      - name: Deploy
        run: helm upgrade --install --set=image.tag=$IMAGE_TAG -f ./charts/promenade-client/$CHART.yaml --debug promenade-client ./charts/promenade-client
